spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/Humming
    username: postgres
    password: postgres
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
      
debug: true
logging:
    level:
        root: INFO
        org:
            springframework.web: DEBUG
            hibernate: INFO
    file: logs/application.log